Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [2]:
#Question 1
import numpy as np 
ls=[1,2,3,4,5]
arr=np.array(ls)
#Part 1
arr+=2
print(arr)
#Part 2
arr*=3
print(arr)
#Part 3
arr=arr/2
print(arr)


[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4.5  6.   7.5  9.  10.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [27]:
#Question 2
ls=[1,2,3,6,5,4]
arr=np.array(ls)
#Part 1
print(arr)
print(arr[::-1])
#Part 2
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_value = np.bincount(x).argmax()
indices = np.where(x == most_frequent_value)[0]
print(x)
print(most_frequent_value)
#Part 3
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])
print(y)
most_frequent_value = np.bincount(y).argmax()
indices = np.where(y== most_frequent_value)[0]
print(most_frequent_value)


[1 2 3 6 5 4]
[4 5 6 3 2 1]
[1 2 3 4 5 1 2 1 1 1]
1
[1 1 1 2 3 4 2 4 3 3 3]
3


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [33]:
#Question 3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(arr[0][1])
print(arr[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [3]:
Your_Name = np.linspace(10, 100, 25)
print("Array:", Your_Name)
print("Dimensions:", Your_Name.ndim)
print("Shape:", Your_Name.shape)
print("Total elements:", Your_Name.size)
print("Data type of elements:", Your_Name.dtype)
print("Total bytes consumed:", Your_Name.nbytes)
Your_Name_transpose = Your_Name.reshape(25, 1)
print("\nTranspose using reshape():\n", Your_Name_transpose)
Your_Name_T = Your_Name.T
print("\nTranspose using T attribute:\n", Your_Name_T)
print("\nUsing T attribute does not change a 1-D array because it has only one axis.")


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of elements: float64
Total bytes consumed: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Using T attribute does not change a 1-D array because it has only one axis.


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [4]:
ucs420_Your_Name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Array:", ucs420_Your_Name)
print("Mean:", np.mean(ucs420_Your_Name))
print("Median:", np.median(ucs420_Your_Name))
print("Max:", np.max(ucs420_Your_Name))
print("Min:", np.min(ucs420_Your_Name))
print("Unique elements:", np.unique(ucs420_Your_Name))
reshaped_ucs420_Your_Name = ucs420_Your_Name.reshape(4, 3)
print("\nReshaped array (4x3):\n", reshaped_ucs420_Your_Name)
resized_ucs420_Your_Name = np.resize(ucs420_Your_Name, (2, 3))
print("\nResized array (2x3):\n", resized_ucs420_Your_Name)

Array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2x3):
 [[10 20 30]
 [40 50 60]]
